<?php
require_once 'PHPUnit/Framework.php';

require_once 'Cage.php';

/**
 * Test class for Inspekt_Cage.
 * Generated by PHPUnit on 2009-08-10 at 16:30:49.
 */
class Inspekt_CageTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var    Inspekt_Cage
	 * @access protected
	 */
	protected $cage;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp()
	{
		$inputarray['html'] = '<IMG """><SCRIPT>alert("XSS")</SCRIPT>">';
        $inputarray['int']  = 7;

		$this->cage = Inspekt_Cage::Factory($inputarray);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown()
	{
	}

	/**
	 * @todo Implement testFactory().
	 */
	public function testFactory()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetIterator().
	 */
	public function testGetIterator()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testOffsetSet().
	 */
	public function testOffsetSet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testOffsetExists().
	 */
	public function testOffsetExists()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testOffsetUnset().
	 */
	public function testOffsetUnset()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testOffsetGet().
	 */
	public function testOffsetGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testCount().
	 */
	public function testCount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testLoadHTMLPurifier().
	 */
	public function testLoadHTMLPurifier()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testSetHTMLPurifier().
	 */
	public function testSetHTMLPurifier()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetHTMLPurifier().
	 */
	public function testGetHTMLPurifier()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_parseAndApplyAutoFilters().
	 */
	public function test_parseAndApplyAutoFilters()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_applyAutoFilters().
	 */
	public function test_applyAutoFilters()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test__call().
	 */
	public function test__call()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * 
	 */
	public function testAddAccessor()
	{
        //pre-condition, clean start
		$this->assertSame($this->cage->_user_accessors, array());
        $this->cage->addAccessor('method_name');
        $this->assertSame($this->cage->_user_accessors, array('method_name'));
	}

	/**
	 * @todo Implement testGetAlpha().
	 */
	public function testGetAlpha()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetAlnum().
	 */
	public function testGetAlnum()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetDigits().
	 */
	public function testGetDigits()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetDir().
	 */
	public function testGetDir()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * 
	 */
	public function testGetInt()
	{
		//non-existent key should return false
		$this->assertFalse($this->cage->getInt('non-existant'));
	}

    /**
	 *
	 */
	public function testGetInt2()
	{
        $this->assertSame($this->cage->getInt('int'), 7);
	}

	/**
	 * @todo Implement testGetPath().
	 */
	public function testGetPath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetROT13().
	 */
	public function testGetROT13()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testGetPurifiedHTML().
	 */
	public function testGetPurifiedHTML()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * 
	 */
	public function testGetRaw()
	{
		$this->assertFalse($this->cage->getRaw('non-existant'));
	}

    /**
	 *
	 */
	public function testGetRaw2()
	{
		//test that found key returns matching value
        $this->assertEquals($this->cage->getRaw('html'),
            '<IMG """><SCRIPT>alert("XSS")</SCRIPT>">');
	}

	/**
	 * 
	 */
	public function testTestAlnum()
	{
		$_POST = array();
		$_POST['b'] = '0';
		$cage_POST = Inspekt::makePostCage();
		$result = $cage_POST->testAlnum('b');
		$this->assertSame('0', $result);
	}

	/**
	 * 
	 */
	public function testTestAlnum2()
	{
		$_POST = array();
		$_POST['b'] = '2009-12-25';
		$cage_POST = Inspekt::makePostCage();
		$result = $cage_POST->testGreaterThan('b', 25);
		$this->assertSame(FALSE, $result);
	}

	/**
	 * 
	 */
	public function testTestAlnum3()
	{
		$_POST = array();
		$_POST['b'] = '0';
		$cage_POST = Inspekt::makePostCage();
		$result = $cage_POST->testLessThan('b', 25);
		$this->assertSame('0', $result);
	}

	/**
	 * @todo Implement testTestAlpha().
	 */
	public function testTestAlpha()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestBetween().
	 */
	public function testTestBetween()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestCcnum().
	 */
	public function testTestCcnum()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestDate().
	 */
	public function testTestDate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestDigits().
	 */
	public function testTestDigits()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestEmail().
	 */
	public function testTestEmail()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestFloat().
	 */
	public function testTestFloat()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestGreaterThan().
	 */
	public function testTestGreaterThan()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestHex().
	 */
	public function testTestHex()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestHostname().
	 */
	public function testTestHostname()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestInt().
	 */
	public function testTestInt()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestIp().
	 */
	public function testTestIp()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestLessThan().
	 */
	public function testTestLessThan()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestOneOf().
	 */
	public function testTestOneOf()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestPhone().
	 */
	public function testTestPhone()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestRegex().
	 */
	public function testTestRegex()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestUri().
	 */
	public function testTestUri()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testTestZip().
	 */
	public function testTestZip()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testNoTags().
	 */
	public function testNoTags()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testNoPath().
	 */
	public function testNoPath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testNoTagsOrSpecial().
	 */
	public function testNoTagsOrSpecial()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testEscMySQL().
	 */
	public function testEscMySQL()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testEscPgSQL().
	 */
	public function testEscPgSQL()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testEscPgSQLBytea().
	 */
	public function testEscPgSQLBytea()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement testKeyExists().
	 */
	public function testKeyExists()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_keyExistsRecursive().
	 */
	public function test_keyExistsRecursive()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_getValue().
	 */
	public function test_getValue()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_getValueRecursive().
	 */
	public function test_getValueRecursive()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_setValue().
	 */
	public function test_setValue()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @todo Implement test_setValueRecursive().
	 */
	public function test_setValueRecursive()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
?>